In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

## Data Cleaning Steps:
    1. Remove duplicate row data
        - check duplicate data --> duplicated()
        - remove duplicate data --> drop_duplicates()

    2. Drop Data
        - If columns contain at least 70-75% Null values then Drop that column.
        - Drop Column --> drop() --> pass column name to drop entire column or pass row index to drop entire row
        - dropna() --> only drop row where NaN value is present, works on passing arguments.

    3. Fill Data
        Fill by Mean, Median or Mode value
        - Continuous Data --> Mean/Median value
        - Discrete / Categorical Data --> Mode value

        - or fill by custom records if neither Mean, Median nor Mode value satisfy to fill.

        - Skewness check --> This gives the value where Mean and Median actually be at same point of value.
            - This help to choose either Mean or Median Value to fill data
            - If skewness value lies between 0 - 0.5 --> Mean value
            - If skewness value is either less than 0 or more than 0.5 --> Median value
            - Check Skewness of column --> skew()

        - fill data --> fillna()

    4. Remove unwanted Data --> remove like unwanted spaces
        - remove whitespaces (only for object/string) --> strip(), lstrip() or rstrip()
        - remove unwanted texts/characters --> replace()

    5. Convert Datatypes (Typecasting)
        - e.g., when data is in csv format then datatime column data always be in text format. So, we need to convert this datatype to datetime format for further analysis.


## After Data Cleaning, further steps are Feature Engineering
    - where columns are combined or split as our requirement

In [5]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

# 1. Remove Duplicate Data

In [7]:
# Check Duplicate Rows
# NOTE: first index always treat as unique row and rest as duplicate row of similar subset
duplicate_data = df[df.duplicated(subset = 'EMPLOYEE_ID')]
duplicate_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [15]:
# cross check duplicate
emp_id = int(input('Enter emp id: '))
data = df[df['EMPLOYEE_ID'] == emp_id]
data

Enter emp id:  203

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0

In [16]:
# Remove Duplicate Row
df.drop_duplicates(subset = 'EMPLOYEE_ID', inplace=True)

In [17]:
# Check duplicate row
duplicate_data = df[df.duplicated(subset = 'EMPLOYEE_ID')]
duplicate_data

Empty DataFrame
Columns: [EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID]
Index: []

In [18]:
# cross check duplicate
emp_id = int(input('Enter emp id: '))
data = df[df['EMPLOYEE_ID'] == emp_id]
data

Enter emp id:  203

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0

In [19]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

# 2. Drop Data
    - dropna() --> only remove Null values
    - drop() --> will remove entire row or column either contain null value or not null value.

In [ ]:
# will drop all the rows where Null value is present.
df.dropna(inplace=True) # Permanent change

In [ ]:
# default
df.dropna()

# For axis:
# 0 -> row
# 1 = column

# For how:
# any -> OR condition
# all -> AND condition

# ROW
# Temporary change, row wise drop, if all column of that row contain Null value
df.dropna(inplace=False, axis=0, how='all')

# Permanent change, row wise drop, if all column of that row contain Null value
df.dropna(inplace=True, axis=0, how='all')

# COLUMN
# Temporary change, column wise drop, if any value contain Null
df.dropna(inplace=False, axis=1, how='any')

# Permanent change, column wise drop, if any value contain Null
df.dropna(inplace=True, axis=1, how='any')

In [ ]:
# drop 
df.drop(columns = ['EMAIL'])

# 3. Fill Data

In [22]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    72
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [23]:
# here 3 columns have Null values

In [24]:
df['COMMISSION_PCT'].skew()

np.float64(0.09661736135041571)

In [ ]:
# here, skew value is 0.09661736135041571 which lies between 0-0.5.
# So, we use Mean value of this column to fill Null values in this column.

In [25]:
comm_mean = round(df['COMMISSION_PCT'].mean(), 2)
comm_mean

np.float64(0.22)

In [ ]:
# fill with Mean value
# choose any method

 # This will directly replace the null value with mean with permanent change
df['COMMISSION_PCT'].fillna(comm_mean, inplace=True)

 # This will create new column if the provided column is not found
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(comm_mean, inplace=True)

 # This will directly replace the null value with mean with permanent change
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(comm_mean)

 # Passing DICT value
df.fillna({'COMMISSION_PCT': comm_mean}, inplace=True)

In [27]:
# There are Discrete Value. So we need Mode of these
mgr_mode = df['MANAGER_ID'].mode()
dept_mode = df['DEPARTMENT_ID'].mode()

print(mgr_mode)
print(dept_mode)

0    100.0
Name: MANAGER_ID, dtype: float64
0    50.0
Name: DEPARTMENT_ID, dtype: float64

In [29]:
# All 3 columns at once
df.fillna({'COMMISSION_PCT': comm_mean}, inplace=True)
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(mgr_mode)
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(dept_mode)

In [30]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     1
dtype: int64

In [33]:
# here still giving 1 value because sometimes mode can be more than once. So program get confuse.
# That's why we must select index 0.

comm_mean = round(df['COMMISSION_PCT'].mean(), 2)
mgr_mode = df['MANAGER_ID'].mode()[0]
dept_mode = df['DEPARTMENT_ID'].mode()[0]

df.fillna({'COMMISSION_PCT': comm_mean}, inplace=True)
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(mgr_mode)
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(dept_mode)

In [34]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

# 4. Remove unwanted Data:

In [35]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,0.22,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [36]:
df['FIRST_NAME'].unique()

<ArrowStringArray>
[     'Steven',       'Neena',         'Lex',   'Alexander',       'Bruce',
       'David',       'Valli',       'Diana',       'Nancy',      'Daniel',
        'John',      'Ismael', 'Jose Manuel',        'Luis',         'Den',
      'Shelli',       'Sigal',         'Guy',       'Karen',     'Matthew',
        'Adam',       'Payam',      'Shanta',       'Kevin',       'Julia',
       'Irene',       'James',       'Laura',       'Mozhe',          'TJ',
       'Jason',     'Michael',          'Ki',       'Hazel',      'Renske',
     'Stephen',      'Joshua',      'Trenna',      'Curtis',     'Randall',
       'Peter',     'Alberto',      'Gerald',       'Eleni', 'Christopher',
     'Nanette',      'Oliver',     'Janette',     'Patrick',       'Allan',
     'Lindsey',      'Louise',      'Sarath',       'Clara',    'Danielle',
      'Mattea',      'Sundar',        'Amit',        'Lisa',    'Harrison',
      'Tayler',     'William',   'Elizabeth',     'Sundita',       'Ellen',
      'Alyssa',    'Jonathon',        'Jack',   'Kimberely',     'Charles',
     'Winston',        'Jean',      'Martha',      'Girard',     'Nandita',
      'Alexis',     'Anthony',       'Kelly',    'Jennifer',     'Timothy',
       'Sarah',     'Britney',      'Samuel',       'Vance',       'Alana',
      'Donald',     'Douglas',         'Pat',       'Susan',     'Hermann',
     'Shelley']
Length: 91, dtype: str

In [37]:
# here no value contain whitespace
# Follow the process to remove whitespace

In [38]:
# select object/string columns only
object_dtype = df.select_dtypes('str')
object_dtype

    FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE      JOB_ID
0       Steven      King     SKING  515.123.4567  6/17/2003     AD_PRES
1        Neena   Kochhar  NKOCHHAR  515.123.4568  9/21/2005       AD_VP
2          Lex   De Haan   LDEHAAN  515.123.4569  1/13/2001       AD_VP
3    Alexander    Hunold   AHUNOLD  590.423.4567   1/3/2006     IT_PROG
4        Bruce     Ernst    BERNST  590.423.4568  5/21/2007     IT_PROG
..         ...       ...       ...           ...        ...         ...
102        Pat       Fay      PFAY  603.123.6666  8/17/2005      MK_REP
103      Susan    Mavris   SMAVRIS  515.123.7777   6/7/2002      HR_REP
104    Hermann      Baer     HBAER  515.123.8888   6/7/2002      PR_REP
105    Shelley   Higgins  SHIGGINS  515.123.8080   6/7/2002      AC_MGR
106    William     Gietz    WGIETZ  515.123.8181   6/7/2002  AC_ACCOUNT

[107 rows x 6 columns]

In [40]:
# Actually in CSV format Datetime column always saved in str format.
# So exclude now
object_dtype.drop(columns = ['PHONE_NUMBER', 'HIRE_DATE'])

    FIRST_NAME LAST_NAME     EMAIL      JOB_ID
0       Steven      King     SKING     AD_PRES
1        Neena   Kochhar  NKOCHHAR       AD_VP
2          Lex   De Haan   LDEHAAN       AD_VP
3    Alexander    Hunold   AHUNOLD     IT_PROG
4        Bruce     Ernst    BERNST     IT_PROG
..         ...       ...       ...         ...
102        Pat       Fay      PFAY      MK_REP
103      Susan    Mavris   SMAVRIS      HR_REP
104    Hermann      Baer     HBAER      PR_REP
105    Shelley   Higgins  SHIGGINS      AC_MGR
106    William     Gietz    WGIETZ  AC_ACCOUNT

[107 rows x 4 columns]

In [41]:
# Manually check unique values in columns
df['FIRST_NAME'].unique()

<ArrowStringArray>
[     'Steven',       'Neena',         'Lex',   'Alexander',       'Bruce',
       'David',       'Valli',       'Diana',       'Nancy',      'Daniel',
        'John',      'Ismael', 'Jose Manuel',        'Luis',         'Den',
      'Shelli',       'Sigal',         'Guy',       'Karen',     'Matthew',
        'Adam',       'Payam',      'Shanta',       'Kevin',       'Julia',
       'Irene',       'James',       'Laura',       'Mozhe',          'TJ',
       'Jason',     'Michael',          'Ki',       'Hazel',      'Renske',
     'Stephen',      'Joshua',      'Trenna',      'Curtis',     'Randall',
       'Peter',     'Alberto',      'Gerald',       'Eleni', 'Christopher',
     'Nanette',      'Oliver',     'Janette',     'Patrick',       'Allan',
     'Lindsey',      'Louise',      'Sarath',       'Clara',    'Danielle',
      'Mattea',      'Sundar',        'Amit',        'Lisa',    'Harrison',
      'Tayler',     'William',   'Elizabeth',     'Sundita',       'Ellen',
      'Alyssa',    'Jonathon',        'Jack',   'Kimberely',     'Charles',
     'Winston',        'Jean',      'Martha',      'Girard',     'Nandita',
      'Alexis',     'Anthony',       'Kelly',    'Jennifer',     'Timothy',
       'Sarah',     'Britney',      'Samuel',       'Vance',       'Alana',
      'Donald',     'Douglas',         'Pat',       'Susan',     'Hermann',
     'Shelley']
Length: 91, dtype: str

In [47]:
# Loop to check all columns unique value at once
columns = ['FIRST_NAME', 'LAST_NAME', 'EMAIL', 'JOB_ID']
for col in columns:
    print(col)
    print('-'*8)
    unique_data = df[col].unique()
    print(unique_data)
    print('\n')

FIRST_NAME
--------
<ArrowStringArray>
[     'Steven',       'Neena',         'Lex',   'Alexander',       'Bruce',
       'David',       'Valli',       'Diana',       'Nancy',      'Daniel',
        'John',      'Ismael', 'Jose Manuel',        'Luis',         'Den',
      'Shelli',       'Sigal',         'Guy',       'Karen',     'Matthew',
        'Adam',       'Payam',      'Shanta',       'Kevin',       'Julia',
       'Irene',       'James',       'Laura',       'Mozhe',          'TJ',
       'Jason',     'Michael',          'Ki',       'Hazel',      'Renske',
     'Stephen',      'Joshua',      'Trenna',      'Curtis',     'Randall',
       'Peter',     'Alberto',      'Gerald',       'Eleni', 'Christopher',
     'Nanette',      'Oliver',     'Janette',     'Patrick',       'Allan',
     'Lindsey',      'Louise',      'Sarath',       'Clara',    'Danielle',
      'Mattea',      'Sundar',        'Amit',        'Lisa',    'Harrison',
      'Tayler',     'William',   'Elizabeth',     'Sundita',       'Ellen',
      'Alyssa',    'Jonathon',        'Jack',   'Kimberely',     'Charles',
     'Winston',        'Jean',      'Martha',      'Girard',     'Nandita',
      'Alexis',     'Anthony',       'Kelly',    'Jennifer',     'Timothy',
       'Sarah',     'Britney',      'Samuel',       'Vance',       'Alana',
      'Donald',     'Douglas',         'Pat',       'Susan',     'Hermann',
     'Shelley']
Length: 91, dtype: str


LAST_NAME
--------
<ArrowStringArray>
[     'King',   'Kochhar',   'De Haan',    'Hunold',     'Ernst',    'Austin',
 'Pataballa',   'Lorentz', 'Greenberg',    'Faviet',
 ...
     'Walsh',    'Feeney',  'OConnell',    'Whalen', 'Hartstein',       'Fay',
    'Mavris',      'Baer',   'Higgins',     'Gietz']
Length: 102, dtype: str


EMAIL
--------
<ArrowStringArray>
[   'SKING', 'NKOCHHAR',  'LDEHAAN',  'AHUNOLD',   'BERNST',  'DAUSTIN',
 'VPATABAL', 'DLORENTZ', 'NGREENBE',  'DFAVIET',
 ...
  'KFEENEY', 'DOCONNEL',   'DGRANT',  'JWHALEN', 'MHARTSTE',     'PFAY',
  'SMAVRIS',    'HBAER', 'SHIGGINS',   'WGIETZ']
Length: 107, dtype: str


JOB_ID
--------
<ArrowStringArray>
[   'AD_PRES',      'AD_VP',    'IT_PROG',     'FI_MGR', 'FI_ACCOUNT',
     'PU_MAN',   'PU_CLERK',     'ST_MAN',   'ST_CLERK',     'SA_MAN',
     'SA_REP',   'SH_CLERK',    'AD_ASST',     'MK_MAN',     'MK_REP',
     'HR_REP',     'PR_REP',     'AC_MGR', 'AC_ACCOUNT']
Length: 19, dtype: str

In [48]:
# Manually remove whitespace
df['FIRST_NAME'] = df['FIRST_NAME'].str.strip()

In [49]:
# Loop to remove whitespace from all cols at once
# using func
def removeWhitespace(dataframe, col_names):
    for col in col_names:
        dataframe[col] = dataframe[col].str.strip()

In [50]:
removeWhitespace(df, columns) # df = our dataframe, columns = already defined and extracted above

In [51]:
# Confirm and check again white space

# Loop to check all columns unique value at once
columns = ['FIRST_NAME', 'LAST_NAME', 'EMAIL', 'JOB_ID']
for col in columns:
    print(col)
    print('-'*8)
    unique_data = df[col].unique()
    print(unique_data)
    print('\n')

FIRST_NAME
--------
<ArrowStringArray>
[     'Steven',       'Neena',         'Lex',   'Alexander',       'Bruce',
       'David',       'Valli',       'Diana',       'Nancy',      'Daniel',
        'John',      'Ismael', 'Jose Manuel',        'Luis',         'Den',
      'Shelli',       'Sigal',         'Guy',       'Karen',     'Matthew',
        'Adam',       'Payam',      'Shanta',       'Kevin',       'Julia',
       'Irene',       'James',       'Laura',       'Mozhe',          'TJ',
       'Jason',     'Michael',          'Ki',       'Hazel',      'Renske',
     'Stephen',      'Joshua',      'Trenna',      'Curtis',     'Randall',
       'Peter',     'Alberto',      'Gerald',       'Eleni', 'Christopher',
     'Nanette',      'Oliver',     'Janette',     'Patrick',       'Allan',
     'Lindsey',      'Louise',      'Sarath',       'Clara',    'Danielle',
      'Mattea',      'Sundar',        'Amit',        'Lisa',    'Harrison',
      'Tayler',     'William',   'Elizabeth',     'Sundita',       'Ellen',
      'Alyssa',    'Jonathon',        'Jack',   'Kimberely',     'Charles',
     'Winston',        'Jean',      'Martha',      'Girard',     'Nandita',
      'Alexis',     'Anthony',       'Kelly',    'Jennifer',     'Timothy',
       'Sarah',     'Britney',      'Samuel',       'Vance',       'Alana',
      'Donald',     'Douglas',         'Pat',       'Susan',     'Hermann',
     'Shelley']
Length: 91, dtype: str


LAST_NAME
--------
<ArrowStringArray>
[     'King',   'Kochhar',   'De Haan',    'Hunold',     'Ernst',    'Austin',
 'Pataballa',   'Lorentz', 'Greenberg',    'Faviet',
 ...
     'Walsh',    'Feeney',  'OConnell',    'Whalen', 'Hartstein',       'Fay',
    'Mavris',      'Baer',   'Higgins',     'Gietz']
Length: 102, dtype: str


EMAIL
--------
<ArrowStringArray>
[   'SKING', 'NKOCHHAR',  'LDEHAAN',  'AHUNOLD',   'BERNST',  'DAUSTIN',
 'VPATABAL', 'DLORENTZ', 'NGREENBE',  'DFAVIET',
 ...
  'KFEENEY', 'DOCONNEL',   'DGRANT',  'JWHALEN', 'MHARTSTE',     'PFAY',
  'SMAVRIS',    'HBAER', 'SHIGGINS',   'WGIETZ']
Length: 107, dtype: str


JOB_ID
--------
<ArrowStringArray>
[   'AD_PRES',      'AD_VP',    'IT_PROG',     'FI_MGR', 'FI_ACCOUNT',
     'PU_MAN',   'PU_CLERK',     'ST_MAN',   'ST_CLERK',     'SA_MAN',
     'SA_REP',   'SH_CLERK',    'AD_ASST',     'MK_MAN',     'MK_REP',
     'HR_REP',     'PR_REP',     'AC_MGR', 'AC_ACCOUNT']
Length: 19, dtype: str

#### Replace character

In [52]:
df['FIRST_NAME']

0         Steven
1          Neena
2            Lex
3      Alexander
4          Bruce
         ...
102          Pat
103        Susan
104      Hermann
105      Shelley
106      William
Name: FIRST_NAME, Length: 107, dtype: str

In [53]:
df['FIRST_NAME'] = df['FIRST_NAME'].str.replace('ven', '***', regex=False)
# In Python, regex always be True. But in Pandas it also be True but either we make False or we have to pass regex

In [54]:
df['FIRST_NAME']

0         Ste***
1          Neena
2            Lex
3      Alexander
4          Bruce
         ...
102          Pat
103        Susan
104      Hermann
105      Shelley
106      William
Name: FIRST_NAME, Length: 107, dtype: str

# 5. Convert Datatypes (Typecasting):
    - NOTE: CSV file always save datetime column into str format.

    Primitive datatype(int, str, float, boolean, none, complex)
        Python:
            a = 34 #int
            a = float(a) #float
        Pandas:
            a.astype(int)

    But datetie column -> to_datetime(col_name, format)
        format->'%d,%m,%y', '%d-%m-%y', 'mixed'

    finally datetime column saved into YYYY-MM-DD

In [55]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Ste***,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,0.22,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     107 non-null    int64
 1   FIRST_NAME      107 non-null    str
 2   LAST_NAME       107 non-null    str
 3   EMAIL           107 non-null    str
 4   PHONE_NUMBER    107 non-null    str
 5   HIRE_DATE       107 non-null    str
 6   JOB_ID          107 non-null    str
 7   SALARY          107 non-null    int64
 8   COMMISSION_PCT  107 non-null    float64
 9   MANAGER_ID      107 non-null    float64
 10  DEPARTMENT_ID   107 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 14.5 KB

In [58]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'], format='mixed')

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     107 non-null    int64
 1   FIRST_NAME      107 non-null    str
 2   LAST_NAME       107 non-null    str
 3   EMAIL           107 non-null    str
 4   PHONE_NUMBER    107 non-null    str
 5   HIRE_DATE       107 non-null    datetime64[us]
 6   JOB_ID          107 non-null    str
 7   SALARY          107 non-null    int64
 8   COMMISSION_PCT  107 non-null    float64
 9   MANAGER_ID      107 non-null    float64
 10  DEPARTMENT_ID   107 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(2), str(5)
memory usage: 13.5 KB

In [60]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Ste***,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,0.22,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0

In [65]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].astype(int)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     107 non-null    int64
 1   FIRST_NAME      107 non-null    str
 2   LAST_NAME       107 non-null    str
 3   EMAIL           107 non-null    str
 4   PHONE_NUMBER    107 non-null    str
 5   HIRE_DATE       107 non-null    datetime64[us]
 6   JOB_ID          107 non-null    str
 7   SALARY          107 non-null    int64
 8   COMMISSION_PCT  107 non-null    float64
 9   MANAGER_ID      107 non-null    float64
 10  DEPARTMENT_ID   107 non-null    int64
dtypes: datetime64[us](1), float64(2), int64(3), str(5)
memory usage: 13.5 KB